---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami-ghost
  namespace: flux-system
spec:
  type: "oci"
  interval: 5m0s
  url: oci://registry-1.docker.io/bitnamicharts/ghost
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitnami-ghost-dev
  namespace: flux-system
spec:
  interval: 30s
  targetNamespace: dev
  chart:
    spec:
      chart: ghost
      version: 20.0.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-ghost
        namespace: flux-system
      interval: 30s
  values:
    mysql:
      enabled: false
