---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami-ghost
  namespace: flux-system
spec:
  type: "oci"
  interval: 5m0s
  url: oci://registry-1.docker.io/bitnamicharts/ghost
